-- Subject taxonomy: people/groups appearing in works.
-- Additive only. Does not replace creators (uploaders/channels).

CREATE TABLE IF NOT EXISTS public.subjects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (type IN ('person', 'group')),
  category text NOT NULL CHECK (category IN ('cheer', 'kpop', 'look')),
  slug text NOT NULL UNIQUE,
  name_ko text,
  name_en text,
  name_zh_tw text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS subjects_category_active_idx
  ON public.subjects (category, active);

CREATE TABLE IF NOT EXISTS public.subject_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id uuid NOT NULL REFERENCES public.subjects (id) ON DELETE CASCADE,
  alias text NOT NULL,
  normalized_alias text NOT NULL,
  language text,
  match_mode text NOT NULL DEFAULT 'substring'
    CHECK (match_mode IN ('substring', 'token')),
  auto_match_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subject_id, normalized_alias)
);

CREATE INDEX IF NOT EXISTS subject_aliases_subject_id_idx
  ON public.subject_aliases (subject_id);

CREATE INDEX IF NOT EXISTS subject_aliases_normalized_alias_idx
  ON public.subject_aliases (normalized_alias);

CREATE TABLE IF NOT EXISTS public.work_subjects (
  work_id bigint NOT NULL REFERENCES public.works (id) ON DELETE CASCADE,
  subject_id uuid NOT NULL REFERENCES public.subjects (id) ON DELETE CASCADE,
  source text NOT NULL
    CHECK (source IN ('manual', 'auto_title', 'auto_description', 'auto_creator')),
  matched_alias text,
  confidence numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (work_id, subject_id)
);

CREATE INDEX IF NOT EXISTS work_subjects_work_id_idx
  ON public.work_subjects (work_id);

CREATE INDEX IF NOT EXISTS work_subjects_subject_id_idx
  ON public.work_subjects (subject_id);

CREATE INDEX IF NOT EXISTS work_subjects_source_idx
  ON public.work_subjects (source);

ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subject_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_subjects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read active subjects"
  ON public.subjects
  FOR SELECT
  TO anon, authenticated
  USING (active = true);

CREATE POLICY "Public read work subjects"
  ON public.work_subjects
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT SELECT ON TABLE public.subjects TO anon;
GRANT SELECT ON TABLE public.subjects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subjects TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subject_aliases TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.subject_aliases_id_seq TO service_role;

GRANT SELECT ON TABLE public.work_subjects TO anon;
GRANT SELECT ON TABLE public.work_subjects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.work_subjects TO service_role;
